export const dataRoad = [
  {
    name: 'Internet',
    p1: 'The Internet is a global network of computers connected to each other which communicate through a standardized set of protocols.',
    p2: 'Visit the following resources to learn more:',
    name_links: ['The Internet Explained', 'How Does the Internet Work?', 'Introduction to Internet', 'How the Internet Works in 5 Minutes'],
    links: [
      'https://medium.com/@sgwethan/the-internet-explained-bbc56ce331f',
      'https://www.geeksforgeeks.org/how-does-the-internet-work/',
      'https://webref.ru/course/introduction',
      'https://www.youtube.com/watch?v=7_LPdttKXPc',
    ],
  },
  {
    name: 'Network',
    p1: 'The Internet is a global network of computers connected to each other which communicate through a standardized set of protocols.',
    p2: 'Visit the following resources to learn more:',
    name_links: ['The Internet Explained', 'How Does the Internet Work?', 'Introduction to Internet', 'How the Internet Works in 5 Minutes'],
    links: [
      'https://medium.com/@sgwethan/the-internet-explained-bbc56ce331f',
      'https://www.geeksforgeeks.org/how-does-the-internet-work/',
      'https://webref.ru/course/introduction',
      'https://www.youtube.com/watch?v=7_LPdttKXPc',
    ],
  },
  {
    name: 'Browser',
    p1: 'A web browser is a software application that enables a user to access and display web pages or other online content through its graphical user interface.',
    p2: 'Visit the following resources to learn more:',
    name_links: ['How Browsers Work', 'Role of Rendering Engine in Browsers', 'Populating the Page: How Browsers Work', 'How Do Web Browsers Work?'],
    links: [
      'https://www.youtube.com/watch?v=gdriDw-ciH8',
      'https://www.browserstack.com/guide/browser-rendering-engine',
      'https://developer.mozilla.org/en-US/docs/Web/Performance/How_browsers_work',
      'https://www.youtube.com/watch?v=WjDrMKZWCt0',
    ],
  },
  {
    name: 'HTTP',
    p1: 'HTTP is the TCP/IP based application layer communication protocol which standardizes how the client and server communicate with each other. HTTP follows a classical “Client-Server model” with a client opening a connection request, then waiting until it receives a response. HTTP is a stateless protocol, that means that the server does not keep any data (state) between two requests.',
    p2: 'Visit the following resources to learn more:',
    name_links: ['What is HTTP?', 'HTTP lecture', 'How HTTPS Works …in a comic', 'An overview of HTTP', 'Journey to HTTP/2', 'HTTP/3 From A To Z: Core Concepts'],
    links: [
      'https://www.cloudflare.com/en-gb/learning/ddos/glossary/hypertext-transfer-protocol-http/',
      'https://www.youtube.com/watch?v=jOUb8wot2sU',
      'https://howhttps.works/',
      'https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview',
      'https://kamranahmed.info/blog/2016/08/13/http-in-depth',
      'HTTP/3 From A To Z: Core Concepts',
    ],
  },
  {
    name: 'Domain',
    p1: 'A domain name is a unique, easy-to-remember address used to access websites, such as ‘google.com’, and ‘facebook.com’. Users can connect to websites using domain names thanks to the Domain Name System (DNS).',
    p2: 'Visit the following resources to learn more:',
    name_links: ['What is a Domain Name?', 'What is a Domain Name? | Domain name vs. URL', 'A Beginners Guide to How Domain Names Work'],
    links: [
      'https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_domain_name',
      'https://www.cloudflare.com/en-gb/learning/dns/glossary/what-is-a-domain-name/',
      'https://www.youtube.com/watch?v=Y4cRx19nhJk',
    ],
  },
  {
    name: 'Hosting',
    p1: 'Web hosting is an online service that allows you to publish your website files onto the internet. So, anyone who has access to the internet has access to your website.',
    p2: 'Visit the following resources to learn more:',
    name_links: ['What Is Web Hosting? Explained', 'Different Types of Web Hosting Explained', 'Where to Host a Fullstack Project on a Budget'],
    links: ['https://www.youtube.com/watch?v=htbY9-yggB0', 'https://www.youtube.com/watch?v=AXVZYzw8geg', 'https://www.youtube.com/watch?v=Kx_1NYYJS7Q'],
  },
  {
    name: 'DNS',
    p1: 'The Domain Name System (DNS) is the phonebook of the Internet. Humans access information online through domain names, like nytimes.com or espn.com. Web browsers interact through Internet Protocol (IP) addresses. DNS translates domain names to IP addresses so browsers can load Internet resources.',
    p2: 'Visit the following resources to learn more:',
    name_links: ['What is DNS?', 'Mess with DNS - DNS Playground', 'How DNS works (comic)', 'DNS and How does it Work?'],
    links: ['https://www.cloudflare.com/en-gb/learning/dns/what-is-dns/', 'https://messwithdns.net/', 'https://howdns.works/', 'https://www.youtube.com/watch?v=Wj0od2ag5sk'],
  },
  {
    name: 'HTML',
    p1: 'HTML stands for HyperText Markup Language. It is used on the frontend and gives the structure to the webpage which you can style using CSS and make interactive using JavaScript.',
    p2: 'Visit the following resources to learn more:',
    name_links: ['W3Schools: Learn HTML', 'htmlreference.io: All HTML elements at a glance', 'HTML For Beginners The Easy Way', 'Web Development Basics'],
    links: ['https://www.w3schools.com/html/html_intro.asp', 'https://htmlreference.io/', 'https://html.com/', 'https://www.internetingishard.com/html-and-css/'],
  },
  {
    name: 'Basics',
    p1: 'HTML stands for HyperText Markup Language. It is used on the frontend and gives the structure to the webpage which you can style using CSS and make interactive using JavaScript.',
    p2: 'Visit the following resources to learn more:',
    name_links: ['HTML Full Course - Build a Website Tutorial', 'HTML Tutorial for Beginners: HTML Crash Course', 'HTML Cheatsheet', 'Scaler: HTML'],
    links: ['https://www.youtube.com/watch?v=pQN-pnXPaVg', 'https://www.youtube.com/watch?v=qz0aGYrrlhU', 'https://htmlcheatsheet.com/', 'https://www.scaler.com/topics/html'],
  },
  {
    name: 'Forms',
    p1: 'Before submitting data to the server, it is important to ensure all required form controls are filled out, in the correct format. This is called client-side form validation, and helps ensure data submitted matches the requirements set forth in the various form controls.',
    p2: 'Visit the following resources to learn more:',
    name_links: ['MDN Web Docs: Client-side form validation', 'Forms lecture', 'Learn Forms by web.dev', 'W3Schools: JavaScript Form Validation'],
    links: [
      'https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation',
      'https://www.youtube.com/watch?v=PhRVJC0kBGE',
      'https://web.dev/learn/forms/',
      'https://www.w3schools.com/js/js_validation.asp',
    ],
  },
  {
    name: 'Semantic',
    p1: 'Semantic element clearly describes its meaning to both the browser and the developer. In HTML, semantic element are the type of elements that can be used to define different parts of a web page such as <form>, <table>, <article>, <header>, <footer>, etc.',
    p2: 'Visit the following resources to learn more:',
    name_links: ['Semantics - MDN Web Docs Glossary: Definitions of Web-related terms | MDN', 'W3Schools: Semantic HTML', 'How To Write Semantic HTML', 'Semantic Markup'],
    links: ['https://developer.mozilla.org/en-US/docs/Glossary/Semantics', 'W3Schools: Semantic HTML', 'How To Write Semantic HTML', 'https://html.com/semantic-markup'],
  },
  {
    name: 'Best Practies',
    p1: 'Learn to follow the best practices for writing maintainable and scalable HTML documents.',
    p2: 'Visit the following resources to learn more:',
    name_links: ['HTML Best Practices', 'General rules for HTML + CSS. Part 1', 'General rules for HTML + CSS. Part 2', 'Generic-principles'],
    links: [
      'https://github.com/hail2u/html-best-practices',
      'https://github.com/rolling-scopes-school/tasks/blob/master/stage1/modules/clean-code/materials/html-and-css.md',
      'https://github.com/rolling-scopes-school/tasks/blob/master/stage1/modules/clean-code/materials/html-and-css-extended.md',
      'https://github.com/rolling-scopes-school/tasks/blob/master/stage1/modules/clean-code/materials/generic-principles.md',
    ],
  },
  {
    name: 'Accessibility',
    p1: 'Web accessibility means that websites, tools, and technologies are designed and developed in such a way that people with disabilities can use them easily.',
    p2: 'Visit the following resources to learn more:',
    name_links: ['Developing for Web Accessibility by W3C WAI', 'Accessibility Tutorial', 'A Complete Guide To Accessible Front-End Components', 'MDN Accessibility'],
    links: [
      'https://www.w3.org/WAI/tips/developing/',
      'https://www.w3schools.com/accessibility/index.php',
      'https://www.smashingmagazine.com/2021/03/complete-guide-accessible-front-end-components/',
      'https://developer.mozilla.org/en-US/docs/Web/Accessibility',
    ],
  },
  {
    name: 'SEO Basic',
    p1: 'SEO or Search Engine Optimization is the technique used to optimize your website for better rankings on search engines such as Google, Bing etc.',
    p2: 'Visit the following resources to learn more:',
    name_links: ['Google Search Central — SEO Docs', 'SEO Guide', 'SEO for Developers', '8 Must-Know SEO Best Practices For Developers'],
    links: [
      'https://developers.google.com/search/docs',
      'https://github.com/seo/guide',
      'https://medium.com/welldone-software/seo-for-developers-a-quick-overview-5b5b7ce34679',
      'https://neilpatel.com/blog/seo-developers/',
    ],
  },
  {
    name: 'CSS',
    p1: 'CSS or Cascading Style Sheets is the language used to style the frontend of any website. CSS is a cornerstone technology of the World Wide Web, alongside HTML and JavaScript.',
    p2: 'Visit the following resources to learn more:',
    name_links: ['CSS-basics', 'CSS Diner (game)', 'HTML/CSS Basics (lecture)', 'HTML and CSS Tutorial', 'W3Schools — Learn CSS', 'CSS Tutorial | Scaler'],
    links: [
      'https://webref.ru/course/css-basics',
      'https://flukeout.github.io/',
      'https://www.youtube.com/watch?v=4Zj7tRlQJao&list=PLzLiprpVuH8df24MzZp-l5QMsJWJbi9qP',
      'https://www.youtube.com/watch?v=D-h8L5hgW-w',
      'https://www.w3schools.com/css/',
      'https://www.scaler.com/topics/css',
    ],
  },
  {
    name: 'Basics CSS',
    p1: 'CSS or Cascading Style Sheets is the language used to style the frontend of any website. CSS is a cornerstone technology of the World Wide Web, alongside HTML and JavaScript.',
    p2: 'Visit the following resources to learn more:',
    name_links: [
      'web.dev — Learn CSS',
      'freeCodeCamp — Responsive Web Design',
      'Learn to Code HTML & CSS',
      'HTML and CSS Tutorial',
      'CSS Crash Course For Absolute Beginners',
      'CSS Masterclass - Tutorial & Course for Beginners',
    ],
    links: [
      'https://web.dev/learn/css/',
      'https://www.freecodecamp.org/learn/responsive-web-design/',
      'https://learn.shayhowe.com/html-css/building-your-first-web-page/',
      'https://www.youtube.com/watch?v=D-h8L5hgW-w',
      'https://www.youtube.com/watch?v=yfoY53QXEnI',
      'https://www.youtube.com/watch?v=FqmB-Zj2-PA',
    ],
  },
  {
    name: 'Layouts',
    p1: 'Float, grid, flexbox, positioning, display and box model are some of the key topics that are used for making layouts. Use the resources below to learn about these topics.',
    p2: 'Visit the following resources to learn more:',
    name_links: [
      'Learn and Practice Flexbox',
      'Game for learning CSS Grid',
      'Game for learning CSS FlexBox',
      'The Box Model',
      'Positioning Types: How Do They Differ?',
      'The CSS Display Property',
      'A Complete Guide to Flexbox',
      'A Complete Guide to Grid',
    ],
    links: [
      'https://flexboxfroggy.com/',
      'https://cssgridgarden.com/',
      'https://flexboxfroggy.com/#ru',
      'https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/The_box_model',
      'https://css-tricks.com/absolute-relative-fixed-positioining-how-do-they-differ/',
      'https://www.freecodecamp.org/news/the-css-display-property-display-none-display-table-inline-block-and-more/',
      'https://css-tricks.com/snippets/css/a-guide-to-flexbox',
      'https://css-tricks.com/snippets/css/complete-guide-grid',
    ],
  },
  {
    name: 'Media Query',
    p1: 'Responsive Web Designing is the technique to make your webpages look good on all screen sizes. There are certain techniques used to achieve that e.g. CSS media queries, percentage widths, min or max widths heights etc.',
    p2: 'Visit the following resources to learn more:',
    name_links: [
      'Responsive Web Design',
      'Learn Responsive Design',
      'The Beginner’s Guide to Responsive Web Design',
      'The guide to responsive web design in 2022',
      '5 simple tips to making responsive layouts the easy way',
      'Introduction To Responsive Web Design',
    ],
    links: [
      'https://www.w3schools.com/css/css_rwd_intro.asp',
      'https://web.dev/learn/design/',
      'https://kinsta.com/blog/responsive-web-design/',
      'https://webflow.com/blog/responsive-web-design',
      'https://www.youtube.com/watch?v=VQraviuwbzU',
      'https://www.youtube.com/watch?v=srvUrASNj0s',
    ],
  },
  {
    name: 'JavaScript',
    p1: 'JavaScript allows you to add interactivity to your pages. Common examples that you may have seen on the websites are sliders, click interactions, popups and so on.',
    p2: 'Visit the following resources to learn more:',
    name_links: [
      'W3Schools – JavaScript Tutorial',
      'The Modern JavaScript Tutorial',
      'Learn JavaScript: Covered many topics',
      'You Dont Know JS Yet (book series)',
      'Modern JavaScript Tutorial',
      'JavaScript for Beginners',
    ],
    links: [
      'https://www.w3schools.com/js/',
      'https://javascript.info/',
      'https://www.javascripttutorial.net/',
      'https://github.com/getify/You-Dont-Know-JS',
      'https://learn.javascript.ru/',
      'https://www.scaler.com/topics/course/javascript-beginners',
    ],
  },
  {
    name: 'Syntax',
    p1: 'JavaScript allows you to add interactivity to your pages. Common examples that you may have seen on the websites are sliders, click interactions, popups and so on.',
    p2: 'Visit the following resources to learn more:',
    name_links: ['W3Schools – JavaScript Tutorial', 'The Modern JavaScript Tutorial', 'JavaScript Crash Course for Beginners', 'Build a Netflix Landing Page Clone with HTML, CSS & JS'],
    links: ['https://www.w3schools.com/js/', 'https://javascript.info/', 'https://youtu.be/hdI2bqOjy3c?t=2', 'https://youtu.be/P7t13SGytRk?t=22'],
  },
  {
    name: 'DOM',
    p1: 'The Document Object Model (DOM) is a programming interface built for HTML and XML documents. It represents the page that allows programs and scripts to dynamically update the document structure, content, and style. With DOM, we can easily access and manipulate tags, IDs, classes, attributes, etc.',
    p2: 'Visit the following resources to learn more:',
    name_links: ['DOM Tree', 'GeeksForGeeks - DOM (Document Object Model)', 'What is the DOM?', 'JavaScript HTML DOM', 'What is DOM, Shadow DOM and Virtual DOM?'],
    links: [
      'https://javascript.info/dom-nodes',
      'https://www.geeksforgeeks.org/dom-document-object-model/',
      'https://www.freecodecamp.org/news/what-is-the-dom-document-object-model-meaning-in-javascript/',
      'https://www.w3schools.com/js/js_htmldom.asp',
      'https://www.youtube.com/watch?v=7Tok22qxPzQ',
    ],
  },
  {
    name: 'AJAX',
    p1: 'Ajax is the technique that lets us send and receive the data asynchronously from the servers e.g. updating the user profile or asynchronously fetching the list of searched products without reloading the page.',
    p2: 'Visit the following resources to learn more:',
    name_links: ['Fetch API MDN Docs', 'A Simple Guide to JavaScript Fetch API', 'Introduction to Fetch', 'JavaScript Fetch API'],
    links: [
      'https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API',
      'https://www.javascripttutorial.net/javascript-fetch-api/',
      'https://web.dev/introduction-to-fetch/',
      'https://www.youtube.com/watch?v=-ZI0ea5O2oA',
    ],
  },
  {
    name: 'ES6+',
    p1: 'ECMAScript 2015 or ES2015 is a significant update to the JavaScript programming language. It is the first major update to the language since ES5 which was standardized in 2009. You should look at the features introduced with ES6 and onwards.',
    p2: 'Visit the following resources to learn more:',
    name_links: ['ES6 Tutorial', 'W3Schools: Javascript ES6', 'Learn Modern JavaScript in 1 Hour', 'JavaScript ES6, ES7, ES8', 'Modern JavaScript ES6, ES7 & ES8'],
    links: [
      'https://www.javascripttutorial.net/es6/',
      'https://www.w3schools.com/js/js_es6.asp',
      'https://www.youtube.com/watch?v=NCwa_xi0Uuc',
      'https://www.youtube.com/watch?v=nZ1DMMsyVyI',
      'https://codeloop.org/learn-modern-javascript-es6-es7-es8',
    ],
  },
  {
    name: 'Git',
    p1: 'Version control systems allow you to track changes to your codebase/files over time. They allow you to go back to some previous version of the codebase without any issues. Also, they help in collaborating with people working on the same code – if you’ve ever collaborated with other people on a project, you might already know the frustration of copying and merging the changes from someone else into your codebase; version control systems allow you to get rid of this issue.',
    p2: 'Visit the following resources to learn more:',
    name_links: ['Version Control System Introduction', 'Git & GitHub Crash Course For Beginners', 'Learn Git in 20 Minutes', 'Git Documentation', 'Learn Git by Atlassian'],
    links: [
      'https://www.youtube.com/watch?v=zbKdDsNNOhg',
      'https://www.youtube.com/watch?v=SWYqp7iY_Tc',
      'https://youtu.be/Y9XZQO1n_7c?t=21',
      'https://git-scm.com/docs',
      'https://www.atlassian.com/git',
    ],
  },
  {
    name: 'GitHub',
    p1: 'GitHub is a provider of internet hosting for software development and version control using Git. It offers the distributed version control and source code management functionality of Git, plus its own features.',
    p2: 'Visit the following resources to learn more:',
    name_links: ['GitHub: Quickstart', 'Learn GitHub by doing', 'What is GitHub?', 'Git vs. GitHub: Whats the difference?', 'Git and GitHub for Beginners'],
    links: [
      'https://docs.github.com/en/get-started/quickstart/hello-world',
      'https://skills.github.com/',
      'https://www.youtube.com/watch?v=w3jLJU7DT5E',
      'https://www.youtube.com/watch?v=wpISo9TNjfU',
      'https://www.atlassian.com/git',
    ],
  },
  {
    name: 'GitLab',
    p1: 'GitLab is a provider of internet hosting for software development and version control using Git. It offers the distributed version control and source code management functionality of Git, plus its own features.',
    p2: 'Visit the following resources to learn more:',
    name_links: ['GitLab Documentation', 'GitLab Website', 'Development: Connect git to GitLab for Small Projects'],
    links: ['https://docs.gitlab.com/', 'https://gitlab.com/', 'https://thenewstack.io/development-connect-git-to-gitlab-for-small-projects/'],
  },
  {
    name: 'Web Security',
    p1: 'Web security refers to the protective measures taken by the developers to protect the web applications from threats that could affect the business.',
    p2: 'Visit the following resources to learn more:',
    name_links: ['Why HTTPS Matters', 'OWASP Web Application Security Testing Checklist', 'OWASP Top 10 Security Risks', 'OWASP Cheatsheets', 'Content Security Policy (CSP)'],
    links: [
      'https://developers.google.com/web/fundamentals/security/encrypt-in-transit/why-https',
      'https://github.com/0xRadi/OWASP-Web-Checklist',
      'https://sucuri.net/guides/owasp-top-10-security-vulnerabilities-2021/',
      'https://cheatsheetseries.owasp.org/cheatsheets/AJAX_Security_Cheat_Sheet.html',
      'https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP',
    ],
  },
  {
    name: 'HTTPS',
    p1: 'HTTPS is a secure way to send data between a web server and a browser. Hypertext transfer protocol secure (HTTPS) is the secure version of HTTP, which is the primary protocol used to send data between a web browser and a website. HTTPS is encrypted in order to increase security of data transfer. This is particularly important when users transmit sensitive data, such as by logging into a bank account, email service, or health insurance provider.',
    p2: 'Visit the following resources to learn more:',
    name_links: ['What is HTTPS?', 'Enabling HTTPS on Your Servers', 'SSL, TLS, HTTP, HTTPS Explained', 'HTTPS — Stories from the field'],
    links: [
      'https://www.cloudflare.com/en-gb/learning/ssl/what-is-https/',
      'https://developers.google.com/web/fundamentals/security/encrypt-in-transit/why-https',
      'https://www.youtube.com/watch?v=hExRDVZHhig',
      'https://www.youtube.com/watch?v=GoXgl9r0Kjk',
    ],
  },
  {
    name: 'CORS',
    p1: 'Cross-Origin Resource Sharing (CORS) is an HTTP-header based mechanism that allows a server to indicate any origins (domain, scheme, or port) other than its own from which a browser should permit loading resources.',
    p2: 'Visit the following resources to learn more:',
    name_links: ['CORS — Cross-Origin Resource Sharing', 'Introducing CORS: Cross-Origin Resource Sharing', 'Cross-Origin Resource Sharing (CORS) - HTTP | MDN'],
    links: ['https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS', 'https://www.youtube.com/watch?v=JVZIhCVFJ9c', 'https://developer.mozilla.org/ru/docs/Web/HTTP/CORS'],
  },
  {
    name: 'GitLab',
    p1: 'GitLab is a provider of internet hosting for software development and version control using Git. It offers the distributed version control and source code management functionality of Git, plus its own features.',
    p2: 'Visit the following resources to learn more:',
    name_links: ['GitLab Documentation', 'GitLab Website', 'Development: Connect git to GitLab for Small Projects'],
    links: ['https://docs.gitlab.com/', 'https://gitlab.com/', 'https://thenewstack.io/development-connect-git-to-gitlab-for-small-projects/'],
  },
  {
    name: 'CSP',
    p1: 'Content Security Policy is a computer security standard introduced to prevent cross-site scripting, clickjacking and other code injection attacks resulting from execution of malicious content in the trusted web page context.',
    p2: 'Visit the following resources to learn more:',
    name_links: ['MDN — Content Security Policy (CSP)', 'Google Devs — Content Security Policy (CSP)', 'Content-Security-Policy Header CSP Reference & Examples'],
    links: ['https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP', 'https://developers.google.com/web/fundamentals/security/csp', 'https://content-security-policy.com/'],
  },
  {
    name: 'OWASP',
    p1: 'OWASP or Open Web Application Security Project is an online community that produces freely-available articles, methodologies, documentation, tools, and technologies in the field of web application security.',
    p2: 'Visit the following resources to learn more:',
    name_links: ['Wikipedia - OWASP', 'OWASP Web Application Security Testing Checklist', 'OWASP Top 10 Security Risks'],
    links: ['https://en.wikipedia.org/wiki/OWASP', 'https://github.com/0xRadi/OWASP-Web-Checklist', 'https://sucuri.net/guides/owasp-top-10-security-vulnerabilities-2021/'],
  },
  {
    name: 'Packages',
    p1: 'Package managers allow you to manage the dependencies (external code written by you or someone else) that your project needs to work correctly.',
    p2: 'Visit the following resources to learn more:',
    name_links: ['Modern JavaScript for Dinosaurs', 'An Absolute Beginners Guide to Using npm'],
    links: ['https://peterxjang.com/blog/modern-javascript-explained-for-dinosaurs.html', 'https://nodesource.com/blog/an-absolute-beginners-guide-to-using-npm/'],
  },
  {
    name: 'NPM',
    p1: 'NPM is a package manager for the JavaScript programming language maintained by npm, Inc. npm is the default package manager for the JavaScript runtime environment Node.js.',
    p2: 'Visit the following resources to learn more:',
    name_links: ['How to NPM', 'NPM tutorial for Beginners', 'NPM Crash Course'],
    links: ['https://github.com/workshopper/how-to-npm', 'https://www.youtube.com/watch?v=2V1UUhBJ62Y', 'https://www.youtube.com/watch?v=jHDhaSSKmB0'],
  },
  {
    name: 'YARN',
    p1: 'Yarn is a software packaging system developed in 2016 by Facebook for Node.js JavaScript runtime environment that provides speed, consistency, stability, and security as an alternative to npm (package manager).',
    p2: 'Visit the following resources to learn more:',
    name_links: ['Yarn - Getting Started', 'Yarn Crash Course'],
    links: ['https://yarnpkg.com/en/docs/getting-started', 'https://www.youtube.com/watch?v=g9_6KmiBISk'],
  },
  {
    name: 'PNPM',
    p1: 'PNPM is an alternative package manager for Node. js which stands for “Performant NPM”. The main purpose of PNPM is to hold all the packages at a global (centralized) store and use them if needed by other projects too by creating hard links to it.',
    p2: 'Visit the following resources to learn more:',
    name_links: ['Official Website', 'Meet PNPM: The Faster, More Performant NPM'],
    links: ['https://pnpm.io/', 'https://blog.bitsrc.io/pnpm-javascript-package-manager-4b5abd59dc9'],
  },
];
