export const dataRoad = [
  {
    name: 'Internet',
    p1: 'The Internet is a global network of computers connected to each other which communicate through a standardized set of protocols.',
    p2: 'Visit the following resources to learn more:',
    name_links: ['The Internet Explained', 'How Does the Internet Work?', 'Introduction to Internet', 'How the Internet Works in 5 Minutes'],
    links: [
      'https://medium.com/@sgwethan/the-internet-explained-bbc56ce331f',
      'https://www.geeksforgeeks.org/how-does-the-internet-work/',
      'https://webref.ru/course/introduction',
      'https://www.youtube.com/watch?v=7_LPdttKXPc',
    ],
  },
  {
    name: 'Network',
    p1: 'The Internet is a global network of computers connected to each other which communicate through a standardized set of protocols.',
    p2: 'Visit the following resources to learn more:',
    name_links: ['The Internet Explained', 'How Does the Internet Work?', 'Introduction to Internet', 'How the Internet Works in 5 Minutes'],
    links: [
      'https://medium.com/@sgwethan/the-internet-explained-bbc56ce331f',
      'https://www.geeksforgeeks.org/how-does-the-internet-work/',
      'https://webref.ru/course/introduction',
      'https://www.youtube.com/watch?v=7_LPdttKXPc',
    ],
  },
  {
    name: 'Browser',
    p1: 'A web browser is a software application that enables a user to access and display web pages or other online content through its graphical user interface.',
    p2: 'Visit the following resources to learn more:',
    name_links: ['How Browsers Work', 'Role of Rendering Engine in Browsers', 'Populating the Page: How Browsers Work', 'How Do Web Browsers Work?'],
    links: [
      'https://www.youtube.com/watch?v=gdriDw-ciH8',
      'https://www.browserstack.com/guide/browser-rendering-engine',
      'https://developer.mozilla.org/en-US/docs/Web/Performance/How_browsers_work',
      'https://www.youtube.com/watch?v=WjDrMKZWCt0',
    ],
  },
  {
    name: 'HTTP',
    p1: 'HTTP is the TCP/IP based application layer communication protocol which standardizes how the client and server communicate with each other. HTTP follows a classical “Client-Server model” with a client opening a connection request, then waiting until it receives a response. HTTP is a stateless protocol, that means that the server does not keep any data (state) between two requests.',
    p2: 'Visit the following resources to learn more:',
    name_links: ['What is HTTP?', 'HTTP lecture', 'How HTTPS Works …in a comic', 'An overview of HTTP', 'Journey to HTTP/2', 'HTTP/3 From A To Z: Core Concepts'],
    links: [
      'https://www.cloudflare.com/en-gb/learning/ddos/glossary/hypertext-transfer-protocol-http/',
      'https://www.youtube.com/watch?v=jOUb8wot2sU',
      'https://howhttps.works/',
      'https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview',
      'https://kamranahmed.info/blog/2016/08/13/http-in-depth',
      'HTTP/3 From A To Z: Core Concepts',
    ],
  },
  {
    name: 'Domain',
    p1: 'A domain name is a unique, easy-to-remember address used to access websites, such as ‘google.com’, and ‘facebook.com’. Users can connect to websites using domain names thanks to the Domain Name System (DNS).',
    p2: 'Visit the following resources to learn more:',
    name_links: ['What is a Domain Name?', 'What is a Domain Name? | Domain name vs. URL', 'A Beginners Guide to How Domain Names Work'],
    links: [
      'https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_domain_name',
      'https://www.cloudflare.com/en-gb/learning/dns/glossary/what-is-a-domain-name/',
      'https://www.youtube.com/watch?v=Y4cRx19nhJk',
    ],
  },
  {
    name: 'Hosting',
    p1: 'Web hosting is an online service that allows you to publish your website files onto the internet. So, anyone who has access to the internet has access to your website.',
    p2: 'Visit the following resources to learn more:',
    name_links: ['What Is Web Hosting? Explained', 'Different Types of Web Hosting Explained', 'Where to Host a Fullstack Project on a Budget'],
    links: ['https://www.youtube.com/watch?v=htbY9-yggB0', 'https://www.youtube.com/watch?v=AXVZYzw8geg', 'https://www.youtube.com/watch?v=Kx_1NYYJS7Q'],
  },
  {
    name: 'DNS',
    p1: 'The Domain Name System (DNS) is the phonebook of the Internet. Humans access information online through domain names, like nytimes.com or espn.com. Web browsers interact through Internet Protocol (IP) addresses. DNS translates domain names to IP addresses so browsers can load Internet resources.',
    p2: 'Visit the following resources to learn more:',
    name_links: ['What is DNS?', 'Mess with DNS - DNS Playground', 'How DNS works (comic)', 'DNS and How does it Work?'],
    links: ['https://www.cloudflare.com/en-gb/learning/dns/what-is-dns/', 'https://messwithdns.net/', 'https://howdns.works/', 'https://www.youtube.com/watch?v=Wj0od2ag5sk'],
  },
  {
    name: 'HTML',
    p1: 'HTML stands for HyperText Markup Language. It is used on the frontend and gives the structure to the webpage which you can style using CSS and make interactive using JavaScript.',
    p2: 'Visit the following resources to learn more:',
    name_links: ['W3Schools: Learn HTML', 'htmlreference.io: All HTML elements at a glance', 'HTML For Beginners The Easy Way', 'Web Development Basics'],
    links: ['https://www.w3schools.com/html/html_intro.asp', 'https://htmlreference.io/', 'https://html.com/', 'https://www.internetingishard.com/html-and-css/'],
  },
  {
    name: 'Basics',
    p1: 'HTML stands for HyperText Markup Language. It is used on the frontend and gives the structure to the webpage which you can style using CSS and make interactive using JavaScript.',
    p2: 'Visit the following resources to learn more:',
    name_links: ['HTML Full Course - Build a Website Tutorial', 'HTML Tutorial for Beginners: HTML Crash Course', 'HTML Cheatsheet', 'Scaler: HTML'],
    links: ['https://www.youtube.com/watch?v=pQN-pnXPaVg', 'https://www.youtube.com/watch?v=qz0aGYrrlhU', 'https://htmlcheatsheet.com/', 'https://www.scaler.com/topics/html'],
  },
  {
    name: 'Forms',
    p1: 'Before submitting data to the server, it is important to ensure all required form controls are filled out, in the correct format. This is called client-side form validation, and helps ensure data submitted matches the requirements set forth in the various form controls.',
    p2: 'Visit the following resources to learn more:',
    name_links: ['MDN Web Docs: Client-side form validation', 'Forms lecture', 'Learn Forms by web.dev', 'W3Schools: JavaScript Form Validation'],
    links: [
      'https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation',
      'https://www.youtube.com/watch?v=PhRVJC0kBGE',
      'https://web.dev/learn/forms/',
      'https://www.w3schools.com/js/js_validation.asp',
    ],
  },
  {
    name: 'Semantic',
    p1: 'Semantic element clearly describes its meaning to both the browser and the developer. In HTML, semantic element are the type of elements that can be used to define different parts of a web page such as <form>, <table>, <article>, <header>, <footer>, etc.',
    p2: 'Visit the following resources to learn more:',
    name_links: ['Semantics - MDN Web Docs Glossary: Definitions of Web-related terms | MDN', 'W3Schools: Semantic HTML', 'How To Write Semantic HTML', 'Semantic Markup'],
    links: ['https://developer.mozilla.org/en-US/docs/Glossary/Semantics', 'W3Schools: Semantic HTML', 'How To Write Semantic HTML', 'https://html.com/semantic-markup'],
  },
  {
    name: 'Best Practies',
    p1: 'Learn to follow the best practices for writing maintainable and scalable HTML documents.',
    p2: 'Visit the following resources to learn more:',
    name_links: ['HTML Best Practices', 'General rules for HTML + CSS. Part 1', 'General rules for HTML + CSS. Part 2', 'Generic-principles'],
    links: [
      'https://github.com/hail2u/html-best-practices',
      'https://github.com/rolling-scopes-school/tasks/blob/master/stage1/modules/clean-code/materials/html-and-css.md',
      'https://github.com/rolling-scopes-school/tasks/blob/master/stage1/modules/clean-code/materials/html-and-css-extended.md',
      'https://github.com/rolling-scopes-school/tasks/blob/master/stage1/modules/clean-code/materials/generic-principles.md',
    ],
  },
  {
    name: 'Accessibility',
    p1: 'Web accessibility means that websites, tools, and technologies are designed and developed in such a way that people with disabilities can use them easily.',
    p2: 'Visit the following resources to learn more:',
    name_links: ['Developing for Web Accessibility by W3C WAI', 'Accessibility Tutorial', 'A Complete Guide To Accessible Front-End Components', 'MDN Accessibility'],
    links: [
      'https://www.w3.org/WAI/tips/developing/',
      'https://www.w3schools.com/accessibility/index.php',
      'https://www.smashingmagazine.com/2021/03/complete-guide-accessible-front-end-components/',
      'https://developer.mozilla.org/en-US/docs/Web/Accessibility',
    ],
  },
  {
    name: 'SEO Basic',
    p1: 'SEO or Search Engine Optimization is the technique used to optimize your website for better rankings on search engines such as Google, Bing etc.',
    p2: 'Visit the following resources to learn more:',
    name_links: ['Google Search Central — SEO Docs', 'SEO Guide', 'SEO for Developers', '8 Must-Know SEO Best Practices For Developers'],
    links: [
      'https://developers.google.com/search/docs',
      'https://github.com/seo/guide',
      'https://medium.com/welldone-software/seo-for-developers-a-quick-overview-5b5b7ce34679',
      'https://neilpatel.com/blog/seo-developers/',
    ],
  },
  {
    name: 'CSS',
    p1: 'CSS or Cascading Style Sheets is the language used to style the frontend of any website. CSS is a cornerstone technology of the World Wide Web, alongside HTML and JavaScript.',
    p2: 'Visit the following resources to learn more:',
    name_links: ['CSS-basics', 'CSS Diner (game)', 'HTML/CSS Basics (lecture)', 'HTML and CSS Tutorial', 'W3Schools — Learn CSS', 'CSS Tutorial | Scaler'],
    links: [
      'https://webref.ru/course/css-basics',
      'https://flukeout.github.io/',
      'https://www.youtube.com/watch?v=4Zj7tRlQJao&list=PLzLiprpVuH8df24MzZp-l5QMsJWJbi9qP',
      'https://www.youtube.com/watch?v=D-h8L5hgW-w',
      'https://www.w3schools.com/css/',
      'https://www.scaler.com/topics/css',
    ],
  },
  {
    name: 'Basics CSS',
    p1: 'CSS or Cascading Style Sheets is the language used to style the frontend of any website. CSS is a cornerstone technology of the World Wide Web, alongside HTML and JavaScript.',
    p2: 'Visit the following resources to learn more:',
    name_links: [
      'web.dev — Learn CSS',
      'freeCodeCamp — Responsive Web Design',
      'Learn to Code HTML & CSS',
      'HTML and CSS Tutorial',
      'CSS Crash Course For Absolute Beginners',
      'CSS Masterclass - Tutorial & Course for Beginners',
    ],
    links: [
      'https://web.dev/learn/css/',
      'https://www.freecodecamp.org/learn/responsive-web-design/',
      'https://learn.shayhowe.com/html-css/building-your-first-web-page/',
      'https://www.youtube.com/watch?v=D-h8L5hgW-w',
      'https://www.youtube.com/watch?v=yfoY53QXEnI',
      'https://www.youtube.com/watch?v=FqmB-Zj2-PA',
    ],
  },
];
